SHOW TABLES IN DATABASE tasty_bytes_dbt_db;
SHOW VIEWS IN DATABASE tasty_bytes_dbt_db;


-- CREATE AUTHENTICATION POLICY mfa_override_policy
-- MFA_ENROLLMENT = 'OPTIONAL'
-- MFA_AUTHENTICATION_METHODS = ('PASSWORD');

-- SELECT CURRENT_ACCOUNT_NAME();
ALTER USER SANJEEEB022 SET RSA_PUBLIC_KEY='-----BEGIN PUBLIC KEY-----
MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAhDzuwcPoipaIsgvVtGSR
rI6ddwVIOBYtlK5wSUHRFI1yg1cFMSiOANudVouJX6kySYsIY9GSAMxHjH6ElXgi
FpStnQHne1qzcAIL8rhJPBBeNrzyzQF8yMzJwkyh6vx+JuaeSHnI7Fy4cCzcuM5R
LoKFqF9p2UumtXGfnBD8vR8cAcE79XdHzAvOPou3vK8wktAUYjxczsayL8gMoIVN
/3Dz/nHmscx6DgiDQlSTSJ7xQcEtZ32rgEhrDOWpPbxMYGhow6+2jztzIAFmJ+bk
qCcOlWhPpYxiNQeDXWfwXV+XQMFPstO79QfLHohQSlgFv1fQqd/9W2o9s86gtaw4
gRugZnGzKjjVgxjXPRaAo9Sp4A3A/eRUoUKaaEVtAK2Z+QWA7jj0nw8ksEX7eXTK
CljgtsbxW9O0onmZqEBjcIPPLTH1NxJpSHk2Zt0Zqwdynec/AGVGOJqunJcF2+Nx
eKSkkjauzQnY2kr6fKAOjAvaavsi1cxRcIrU8H/mGiteW2kOgFYQM8Y9i6j8v452
PbADwj9OGYslLtsLnHujY2uAzRSubdBhWUQjESUeBsmxhCEt1c+YdrzdspS5SkgO
8euiSziKtUppAxLAd/d4xIWAraKd2I6FndG9Lewktzy5aKiQfx87i7CK1GDUG3/f
SEsM6gQQqV8UUmF+mV2a86cCAwEAAQ==
-----END PUBLIC KEY-----';

SHOW USERS LIKE 'SANJEEEB022';
