SELECT
  c.CUSTOMER_ID,
  c.FIRST_NAME,
  c.LAST_NAME,
  c.E_MAIL,
  c.PHONE_NUMBER,
  c.POSTAL_CODE,
  c.GENDER,
  c.MARITAL_STATUS,
  c.SIGN_UP_DATE,
  ct.CITY,
  ct.CITY_POPULATION
FROM TASTY_BYTES_DBT_DB.RAW.CUSTOMER_LOYALTY c
LEFT JOIN TASTY_BYTES_DBT_DB.RAW.COUNTRY ct ON c.COUNTRY = ct.COUNTRY
; -- or join on COUNTRY_ID if available
